In [1]:
import pandas as pd

In [2]:
info = {
    "Name" : ["Rahul","Harshita","Aditee"],
    "CGPA" : [9.5,7.8,8.9]
}
df3 = pd.DataFrame(info)
print(df3)

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.8
2    Aditee   8.9

In [4]:
df3

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.8
2    Aditee   8.9

In [5]:
lis = [1,2,4,5,8]
s = pd.Series(lis)
d= pd.Series(lis,index = ["A","C","F","34","sd"])
print(d)
print(d["34"]) #from Label i.e Custom Index
print(s[3])

A     1
C     2
F     4
34    5
sd    8
dtype: int64
5
5

In [6]:
info2 = {
    "Name" : ["Rahul","Harshita","Aditee"],
    "CGPA" : [9.5,7.8,8.9],
    "Age" : [34,54,79]
}
pd.DataFrame(info2)

       Name  CGPA  Age
0     Rahul   9.5   34
1  Harshita   7.8   54
2    Aditee   8.9   79

In [7]:
info3 = [["Adam",23],["Eve",89],["Rakesh",90]]
pd.DataFrame(info3,columns = ["Name","Age"],index = ["A",98,90])

      Name  Age
A     Adam   23
98     Eve   89
90  Rakesh   90

In [8]:
x=pd.read_csv("employee_data.csv")  
df2 = pd.DataFrame(x)
df2

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [9]:
#Methods
df2.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [10]:
df2.head(3)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000

In [11]:
df2.tail()

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [12]:
df2.tail(2)

   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [13]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 532.0 bytes

In [14]:
df2.shape #return tuple of (rows,column)

(10, 5)

In [15]:
df2.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [16]:
df2.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')

In [17]:
df2.nunique() #Methods over

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [18]:
#AQI DaataSets
df = pd.read_csv("globalAirQuality.csv")
print(df.head())
df.tail()
df.describe()
df.info()
df.nunique()

                    timestamp country      city  latitude  longitude    pm25  \
0  2025-11-04 18:25:17.554219      US  New York    40.713    -74.006  50.295
1  2025-11-04 19:25:17.554219      US  New York    40.713    -74.006  32.083
2  2025-11-04 20:25:17.554219      US  New York    40.713    -74.006  42.250
3  2025-11-04 21:25:17.554219      US  New York    40.713    -74.006  30.403
4  2025-11-04 22:25:17.554219      US  New York    40.713    -74.006  21.083

      pm10     no2    so2      o3     co  aqi  temperature  humidity  \
0  108.938  27.998  6.539  52.568  1.096  108       18.504    70.168
1   63.043  36.120  4.021  43.536  1.075   90        5.838    80.088
2   82.553  26.935  9.538  23.320  0.977   84       31.833    62.783
3   79.951  63.536  7.609  31.369  0.230  158       23.140    89.153
4   66.423  38.997  6.919  45.615  1.085   97       13.632    76.499

   wind_speed
0       3.725
1       8.969
2       9.650
3       8.956
4       4.017
<class 'pandas.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    18000 non-null  str
 1   country      18000 non-null  str
 2   city         18000 non-null  str
 3   latitude     18000 non-null  float64
 4   longitude    18000 non-null  float64
 5   pm25         18000 non-null  float64
 6   pm10         18000 non-null  float64
 7   no2          18000 non-null  float64
 8   so2          18000 non-null  float64
 9   o3           18000 non-null  float64
 10  co           18000 non-null  float64
 11  aqi          18000 non-null  int64
 12  temperature  18000 non-null  float64
 13  humidity     18000 non-null  float64
 14  wind_speed   18000 non-null  float64
dtypes: float64(11), int64(1), str(3)
memory usage: 2.1 MB

timestamp        360
country           38
city              50
latitude          50
longitude         50
pm25           15839
pm10           16332
no2            15139
so2             8158
o3             15275
co              1376
aqi              178
temperature    13930
humidity       15725
wind_speed      8058
dtype: int64

In [19]:
#Selecting Data
df[["country","aqi","country","humidity"]] #selecting multiple column

      country  aqi country  humidity
0          US  108      US    70.168
1          US   90      US    80.088
2          US   84      US    62.783
3          US  158      US    89.153
4          US   97      US    76.499
...       ...  ...     ...       ...
17995      CH  103      CH    52.443
17996      CH  105      CH    85.678
17997      CH  122      CH    72.311
17998      CH   95      CH    31.880
17999      CH   88      CH    59.104

[18000 rows x 4 columns]

In [20]:

df.loc[2]
df.loc[0:2] #str indx : end indx (inclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [21]:
df.iloc[4]
df.iloc[0:2] #str indx : end indx (exclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [22]:
df.loc[0:2,["city","aqi"]]

       city  aqi
0  New York  108
1  New York   90
2  New York   84

In [23]:
df.columns
df.iloc[0:2,[2,4]] # iloc need numeric index to find the cells not string or character values

       city  longitude
0  New York    -74.006
1  New York    -74.006

In [24]:
df.at[0,"city"] #single cell ki value aati hai

'New York'

In [25]:
df.iat[0,2]

'New York'

In [26]:
 #filtering
df[df["aqi"]>100]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [27]:
df[(df["aqi"]>100)& (df["temperature"]>30)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

In [28]:
aqiDA = df[(df["aqi"]>100)&(df["temperature"]>30)] [["city","aqi"]]
aqiDA
# aqiDA.loc(0) show error
aqiDA.iloc[0]
aqiDA.loc[6]

city    New York
aqi          155
Name: 6, dtype: object

In [33]:
#cleaning The Data
#1) Misssing Values
df = pd.read_csv("raw_data.csv")
df.isnull()
df.isna()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [33]:
#cleaning The Data
#1) Misssing Values
df = pd.read_csv("raw_data.csv")
df.isnull()
df.isna()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [34]:
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [35]:
df.dropna()

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [44]:
df.dropna(axis=1)  #important step to remember for changing values
corr  = df.copy()
corr["age"] = corr["age"].fillna(df["age"].mean())
corr

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [55]:
#handling Duplicates
df.duplicated()
df["country"].duplicated()
df[["country","gender"]].duplicated()
df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [54]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [56]:
#handling Strings
df["name"].str.lower()

0         john doe
2       jane smith
3             alex
4     maria garcia
5           li wei
6              NaN
7       ahmed khan
8       rachel lee
9      carlos ruiz
10     emily davis
Name: name, dtype: str

In [57]:
df["name"].str.upper()

0         JOHN DOE
2       JANE SMITH
3             ALEX
4     MARIA GARCIA
5           LI WEI
6              NaN
7       AHMED KHAN
8       RACHEL LEE
9      CARLOS RUIZ
10     EMILY DAVIS
Name: name, dtype: str

In [63]:
df["name"].str.capitalize()

0         John doe
2       Jane smith
3             Alex
4     Maria garcia
5           Li wei
6              NaN
7       Ahmed khan
8       Rachel lee
9      Carlos ruiz
10     Emily davis
Name: name, dtype: str

In [62]:
df["name"].str.strip()

0         John Doe
2       Jane Smith
3             Alex
4     Maria Garcia
5           Li Wei
6              NaN
7       Ahmed Khan
8       Rachel Lee
9      Carlos Ruiz
10     Emily Davis
Name: name, dtype: str

In [64]:
df["name"].str.split(" ")

0         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [66]:
df["country"].str.contains("Us",case = False)

0      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
Name: country, dtype: bool

In [77]:
#handling data type
df["name"].dtypes
df.dtypes
df2 = df.copy()
df2["income"].fillna(0)
df2["income"].astype("Int64")

0     55000
2     62000
3     47000
4      <NA>
5     51000
6     73000
7     68000
8     62000
9     45000
10    58000
Name: income, dtype: Int64